# Generated by Django 4.1 on 2023-10-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(migrations.RunSQL.noop, reverse_sql=migrations.RunSQL.noop),
    ]
