# Generated by Django 4.1 on 2024-04-16 17:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forecaster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resolutions",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
